---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: production
  namespace: flux-system
spec:
  interval: 30s
  ref:
    branch: main
  url: https://github.com/elkrammer/flux-production-demo

---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: "true"
  namespace: flux-system
spec:
  interval: 30s
  path: ./
  prune: true
  sourceRef:
    kind: GitRepository
    name: production
  validation: client

